### PR TITLE
Added avrdude fuse option

### LINKED ISSUE #6: Add avrdude-fuses and avrdude-all
Hi,
I am currently developing a device that requires to set special lock fuse bits after programming.
But I also need to upload an eeprom file. Locking the device before uploading the eeprom is a bad idea.

So it would be nice if you can:
- Program the device (make avrdude)
- Program eeprom (make avrude-ee)
- Set fuses (make avrdude-fuses)
- Use all of those in a row (make avrdude-all)

I already implemented a really quick fix for this:

``` make
# Programs in the target fuses using AVRDUDE
avrdude-fuses: $(MAKEFILE_LIST)
    @echo $(MSG_AVRDUDE_CMD) Programming device \"$(MCU)\" fuses using \"$(AVRDUDE_PROGRAMMER)\" on port \"$(AVRDUDE_PORT)\"
    avrdude $(BASE_AVRDUDE_FLAGS) $(AVRDUDE_FUSES) $(AVRDUDE_FLAGS)

avrdude-all: avrdude avrdude-ee avrdude-fuses
```

However it would be more nice to not expose the U:lfuse etc options tot he user. You'd need some magic if(fuse defined) then use param in avrdude.I have not done it because I dont know how to do it and it worked like this. If you can add this feature it would be super nice and helpful :)

### PR DESCRIPTION
**Pull request by NicoHood**
This should fix #6
You'd have to add the docs, but that is all.

### CODE REVIEW

**Comment by NicoHood** [comment]
This would also make lufa simpler, if you add the special bootloader fuses to the makefile.
Any chance to see it?

**Comment by NicoHood** [comment]
Is there anything you'd change with this? If its only about the missing docs, I could also add them. I just din't want to write them if the changes are not wanted like this.

**Comment by NicoHood** [comment]
Push?

**Comment by abcminiuser** [comment]
GitHub *really*, *really* needs an overview that shows all open issues and pull requests across all account repositories, since I keep forgetting about these once I've read the initial notification. Sorry!

**Comment by abcminiuser** [comment]
Would you mind updating the docs for the new options?

**Comment by NicoHood** [comment]
see #19

**Pull request merged**
