### PR TITLE
 Repair LTO option for linker

### PR DESCRIPTION
**Pull request by dudanov**

### CODE REVIEW

**Comment by NicoHood** [comment]
Why did you move the LTO option further down?

**Comment by dudanov** [comment]
Because BASE_LD_FLAGS is reassigned below. Look closely. ;)

**Comment by NicoHood** [comment]
True! It still worked for me always... (it was my patch). I am wondering why!? Or maybe some newer patches changed the behavior? Or LD flags are not even required?

**Comment by dudanov** [comment]
It is a link-time optimization option (LTO). Usually it is not required. And by default it's off. I accidentally discovered an error. So I decided if there is a mistake, then there must be a correction.

I add bootloader support option. Easy to use.

**Comment by abcminiuser** [comment]
The LTO fix is a good one! Can you please split the other change into its own pull request, so they can be merged separately?

**Comment by dudanov** [comment]
New pull-request created.

**Pull request closed without merging**
